apiVersion: build.dana.io/v1alpha1
kind: ImageBuildPolicy
metadata:
  name: image-build-policy
spec:
  clusterBuildStrategy:
    buildFile:
      present: "buildah-strategy-managed-push"
      absent: "buildpacks-v3"
  retention:
    succeededLimit: 10
