controllerManager:
  image:
    # -- Controller manager container image repository.
    repository: ghcr.io/dana-team/image-builder-operator
    # -- Controller manager container image tag. Defaults to .Chart.AppVersion if empty.
    tag: ""
    # -- Controller manager container image pull policy.
    imagePullPolicy: IfNotPresent

  # -- Number of replicas for the controller manager Deployment.
  replicas: 1

  # -- Resource requests/limits for the controller manager container.
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

# -- Configuration for ImageBuildPolicy CRD
imageBuildPolicy:
  # -- Enable or disable creation of the ImageBuildPolicy resource by Helm.
  enabled: true

  clusterBuildStrategy:
    buildFile:
      # -- Strategy name when the source indicates a file-based build.
      present: buildah-strategy-managed-push
      # -- Strategy name when the source does not indicate a file-based build.
      absent: buildpacks-v3

onCommit:
  # -- Enable OnCommit webhook triggers and associated service.
  enabled: false
