{{- if .Values.imageBuildPolicy.enabled -}}
apiVersion: build.dana.io/v1alpha1
kind: ImageBuildPolicy
metadata:
  name: image-build-policy
  labels:
  {{- include "image-builder-operator.labels" . | nindent 4 }}
spec:
  clusterBuildStrategy:
    buildFile:
      present: {{ .Values.imageBuildPolicy.clusterBuildStrategy.buildFile.present }}
      absent: {{ .Values.imageBuildPolicy.clusterBuildStrategy.buildFile.absent }}
{{- end }}
