apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "image-builder-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: image-builder-operator
    app.kubernetes.io/part-of: image-builder-operator
  {{- include "image-builder-operator.labels" . | nindent 4 }}
