apiVersion: build.dana.io/v1alpha1
kind: ImageBuildPolicy
metadata:
  name: imagebuildpolicy-sample
spec:
  clusterBuildStrategy:
    buildFile:
      present: buildah-strategy-managed-push
      absent: buildpacks-v3
  retention:
    failedLimit: 5
    succeededLimit: 10
    ttlAfterFailed: 72h
    ttlAfterSucceeded: 168h
