apiVersion: build.dana.io/v1alpha1
kind: ImageBuildPolicy
metadata:
  name: imagebuildpolicy-sample
spec:
  clusterBuildStrategy:
    buildFile:
      present: buildah-strategy-managed-push
      absent: buildpacks-v3
