//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuild) DeepCopyInto(out *ImageBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuild.
func (in *ImageBuild) DeepCopy() *ImageBuild {
	if in == nil {
		return nil
	}
	out := new(ImageBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildClusterStrategy) DeepCopyInto(out *ImageBuildClusterStrategy) {
	*out = *in
	out.BuildFile = in.BuildFile
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildClusterStrategy.
func (in *ImageBuildClusterStrategy) DeepCopy() *ImageBuildClusterStrategy {
	if in == nil {
		return nil
	}
	out := new(ImageBuildClusterStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildFile) DeepCopyInto(out *ImageBuildFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildFile.
func (in *ImageBuildFile) DeepCopy() *ImageBuildFile {
	if in == nil {
		return nil
	}
	out := new(ImageBuildFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildFileStrategy) DeepCopyInto(out *ImageBuildFileStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildFileStrategy.
func (in *ImageBuildFileStrategy) DeepCopy() *ImageBuildFileStrategy {
	if in == nil {
		return nil
	}
	out := new(ImageBuildFileStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildGitSource) DeepCopyInto(out *ImageBuildGitSource) {
	*out = *in
	if in.CloneSecret != nil {
		in, out := &in.CloneSecret, &out.CloneSecret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildGitSource.
func (in *ImageBuildGitSource) DeepCopy() *ImageBuildGitSource {
	if in == nil {
		return nil
	}
	out := new(ImageBuildGitSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildList) DeepCopyInto(out *ImageBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImageBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildList.
func (in *ImageBuildList) DeepCopy() *ImageBuildList {
	if in == nil {
		return nil
	}
	out := new(ImageBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildOnCommit) DeepCopyInto(out *ImageBuildOnCommit) {
	*out = *in
	in.WebhookSecretRef.DeepCopyInto(&out.WebhookSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildOnCommit.
func (in *ImageBuildOnCommit) DeepCopy() *ImageBuildOnCommit {
	if in == nil {
		return nil
	}
	out := new(ImageBuildOnCommit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildOnCommitEvent) DeepCopyInto(out *ImageBuildOnCommitEvent) {
	*out = *in
	in.ReceivedAt.DeepCopyInto(&out.ReceivedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildOnCommitEvent.
func (in *ImageBuildOnCommitEvent) DeepCopy() *ImageBuildOnCommitEvent {
	if in == nil {
		return nil
	}
	out := new(ImageBuildOnCommitEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildOnCommitLastTriggered) DeepCopyInto(out *ImageBuildOnCommitLastTriggered) {
	*out = *in
	in.TriggeredAt.DeepCopyInto(&out.TriggeredAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildOnCommitLastTriggered.
func (in *ImageBuildOnCommitLastTriggered) DeepCopy() *ImageBuildOnCommitLastTriggered {
	if in == nil {
		return nil
	}
	out := new(ImageBuildOnCommitLastTriggered)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildOnCommitStatus) DeepCopyInto(out *ImageBuildOnCommitStatus) {
	*out = *in
	if in.LastReceived != nil {
		in, out := &in.LastReceived, &out.LastReceived
		*out = new(ImageBuildOnCommitEvent)
		(*in).DeepCopyInto(*out)
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = new(ImageBuildOnCommitEvent)
		(*in).DeepCopyInto(*out)
	}
	if in.LastTriggeredBuildRun != nil {
		in, out := &in.LastTriggeredBuildRun, &out.LastTriggeredBuildRun
		*out = new(ImageBuildOnCommitLastTriggered)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildOnCommitStatus.
func (in *ImageBuildOnCommitStatus) DeepCopy() *ImageBuildOnCommitStatus {
	if in == nil {
		return nil
	}
	out := new(ImageBuildOnCommitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildOutput) DeepCopyInto(out *ImageBuildOutput) {
	*out = *in
	if in.PushSecret != nil {
		in, out := &in.PushSecret, &out.PushSecret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildOutput.
func (in *ImageBuildOutput) DeepCopy() *ImageBuildOutput {
	if in == nil {
		return nil
	}
	out := new(ImageBuildOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildPolicy) DeepCopyInto(out *ImageBuildPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildPolicy.
func (in *ImageBuildPolicy) DeepCopy() *ImageBuildPolicy {
	if in == nil {
		return nil
	}
	out := new(ImageBuildPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageBuildPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildPolicyList) DeepCopyInto(out *ImageBuildPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImageBuildPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildPolicyList.
func (in *ImageBuildPolicyList) DeepCopy() *ImageBuildPolicyList {
	if in == nil {
		return nil
	}
	out := new(ImageBuildPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageBuildPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildPolicySpec) DeepCopyInto(out *ImageBuildPolicySpec) {
	*out = *in
	out.ClusterBuildStrategy = in.ClusterBuildStrategy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildPolicySpec.
func (in *ImageBuildPolicySpec) DeepCopy() *ImageBuildPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ImageBuildPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildPolicyStatus) DeepCopyInto(out *ImageBuildPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildPolicyStatus.
func (in *ImageBuildPolicyStatus) DeepCopy() *ImageBuildPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ImageBuildPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildRebuild) DeepCopyInto(out *ImageBuildRebuild) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildRebuild.
func (in *ImageBuildRebuild) DeepCopy() *ImageBuildRebuild {
	if in == nil {
		return nil
	}
	out := new(ImageBuildRebuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildSource) DeepCopyInto(out *ImageBuildSource) {
	*out = *in
	in.Git.DeepCopyInto(&out.Git)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildSource.
func (in *ImageBuildSource) DeepCopy() *ImageBuildSource {
	if in == nil {
		return nil
	}
	out := new(ImageBuildSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildSpec) DeepCopyInto(out *ImageBuildSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.BuildFile = in.BuildFile
	if in.Rebuild != nil {
		in, out := &in.Rebuild, &out.Rebuild
		*out = new(ImageBuildRebuild)
		**out = **in
	}
	in.Output.DeepCopyInto(&out.Output)
	if in.OnCommit != nil {
		in, out := &in.OnCommit, &out.OnCommit
		*out = new(ImageBuildOnCommit)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildSpec.
func (in *ImageBuildSpec) DeepCopy() *ImageBuildSpec {
	if in == nil {
		return nil
	}
	out := new(ImageBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildStatus) DeepCopyInto(out *ImageBuildStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnCommit != nil {
		in, out := &in.OnCommit, &out.OnCommit
		*out = new(ImageBuildOnCommitStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildStatus.
func (in *ImageBuildStatus) DeepCopy() *ImageBuildStatus {
	if in == nil {
		return nil
	}
	out := new(ImageBuildStatus)
	in.DeepCopyInto(out)
	return out
}
