name: unit-test
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - 'OWNERS'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1

    - name: Cache Go tools
      uses: actions/cache@v5
      with:
        path: |
          ./bin
        key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: Run unit-tests
      run: make test
